on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Oldest and newest stable.
        php-version: ['8.1', '8.4']
    name: PHP ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Install PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: ${{ matrix.php-version }}
      - name: Validate composer.json
        run: composer validate --strict
      - name: Cache Composer dependencies
        uses: actions/cache@v4.2.0
        with:
          path: vendor
          key: php-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}
          restore-keys: |
            php-${{ hashFiles('**/composer.json') }}-${{ matrix.php-version }}
            php-${{ hashFiles('**/composer.json') }}
            php
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run unit tests
        run: composer run test
      - name: Static code analysis
        run: composer run test:static
